### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by mkacunha** [getheimdall/heimdall#16]
I would like to use Heimdall, but I am a beginner and the documentation on the home page did not help me. Is there a more explanatory tutorial?

**Comment by MAAARKIN** [comment]
@mkacunha i really recommend to you check the docker mode to put heimdall online to you see the gateway working. We really keeping work to improve the documentation, we will create a slack channel soon to provide more informations in real-time to help more people. I hope that you understand and keep follow this issue. But to start, you have some problem or did something to put heimdall online?

**Comment by MAAARKIN** [comment]
Closed for inactivity
