### ISSUE TITLE
The active Menu Item does not change when browser back button is clicked

### ISSUE THREAD

**Issue by cassioesp** [getheimdall/heimdall#187]
**Describe the bug**
The active Menu Item does not change when browser back button is clicked.

**To Reproduce**
1. Go to 'Main' page.
2. Click on any menu item.
3. Click on your browser back button.
4. Error: The page is refreshed but the active menu item does not change.

**Expected behavior**
Maybe the Menu Item should be sync with actual page.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, Firefox and Edge.
 - Version:

**Comment by MAAARKIN** [comment]
the pull request to solve this problem is open;
