### ISSUE TITLE
Trying to add an entry with numeric value on the end of the URL will return validation error

### ISSUE THREAD

**Issue by arroadie** [getheimdall/heimdall#188]
**Describe the bug**
Url with number returns validation errors

**To Reproduce**
1. Go to /items
2. Click on "Add"
3. Fill all fields and use an url with a number eg: http://hydra2/
4. Validation error will be displayed "The url format is invalid."

**Expected behavior**
Values are accepted and the item is added to the dashboard

**Screenshots**
![screenshot](http://static.thiagocosta.io/screenshots/2019-01-22-08-30-29_1223x837.png)

**Desktop (please complete the following information):**
 - OS: Centos7
 - Browser [e.g. chrome, safari]: Firefox 
 - Version [e.g. 22]: 60.4.0esr (64-bit)

**Additional context**
Heimdall is running in a docker container in debian

**Comment by arroadie** [comment]
Nevermind, homonymous project :)

**Comment by marceloaguiarr** [comment]
No problem, hope you find the help you need ;)
