### ISSUE TITLE
Remove the cloud config from project

### ISSUE THREAD

**Issue by MAAARKIN** [getheimdall/heimdall#193]
**Motivation**

Currently the Cloud Config Project provides a great configuration tool for the Heimdall project, but after testing it extensively in production we saw that it does not gives us the advantages that we need. Using Heimdall with Docker, the properties can be defined in the image and overriden with some Docker orchestration tool (Rancher, ...). In production the properties are not that dynamic. We understand that some configurations will be replicated in both projects (Api and Gateway) but again, this information does not change much. Furthermore, it will be easier for new developers, that will not need a third project executing locally, just set the properties for the Gateway or API as needed.

**Comment by cayohollanda** [comment]
the devops people are thankful for this issue!

**Comment by MAAARKIN** [comment]
#210 fix this issue.
