### ISSUE TITLE
ThreadSafe Singleton

### ISSUE THREAD

**Issue by marceloaguiarr** [getheimdall/heimdall#24]
**The TraceContextHolder class need to be a thread safe singleton**
As a singleton this class holds a instance of itself and has a getInstance method. But strategy used to create the singleton was to add the `synchronized` keyword to the get instance method and check if the instance is created before returning it. This creates a synchronization overhead to every call to the getInstance method.

**Using the Initialization-on-demand holder idiom**
By using the Initialization-on-demand holder idiom we can remove the `synchronized` keyword from the getInstance method and still achieve thread safety by using the JVM class initialization optimizations.

**Another alternative**
Another alternative is to use the Eager Initalization idiom. The diference from the Initialization-on-demand idiom is that the Initialization-on-demand idiom is also a lazy initialization alternative.

**Benchmarks**
I have created a benchmark project with all three strategies that I have cited above. Here is the [link](https://github.com/marceloaguiarr/SingletonBenchmark)

Summary of the results:

|Benchmark                             |Mode | Cnt |  Score |   Error | Units
| :-                                   | :-: | :-: |   :-:  |   :-:   | :-:   
|SingletonBenchmark.EagerHolderBench   |avgt |  10 |  0.065 | ± 0.001 | us/op
|SingletonBenchmark.LazyHolderBench    |avgt |  10 |  0.064 | ± 0.001 | us/op
|SingletonBenchmark.SynchronizedBench  |avgt |  10 | 38.562 | ± 0.171 | us/op

**Comment by marceloaguiarr** [comment]
For this issue I have created a pull request [#12](https://github.com/getheimdall/heimdall/pull/12)

**Comment by MAAARKIN** [comment]
#12 merged

**Comment by MAAARKIN** [comment]
#12 merged
