### ISSUE TITLE
Compilation failure (javax.annotation)https://github.com/getheimdall/heimdall/issues/new?template=Bug_report.md

### ISSUE THREAD

**Issue by claytonpiccinin** [getheimdall/heimdall#270]
**Describe the bug**
Error compiling heimdall-core using "mvn clean install". 

**To Reproduce**
1. Delete the .m2 cache directory
2. Go to 'heimdall-core' directory
3. Compile code with 'mvn clean install'

**Expected behavior**
The expected behavior is to build the project with success using version 2.3.2 as configured in pom.xml

**Screenshots**
![error](https://user-images.githubusercontent.com/13591059/57159881-92c2d780-6dbd-11e9-89eb-d26875b62187.png)

**Desktop**
 - OS: Ubuntu

Link to pull request: https://github.com/getheimdall/heimdall/pull/269

**Comment by MAAARKIN** [comment]
#269 solving this issue. 

thx man.
