### ISSUE TITLE
TransientPropertyValueException when updating an existing Interceptor

### ISSUE THREAD

**Issue by gBarczyszyn** [getheimdall/heimdall#286]
**Describe the bug**
Heimdall API thorws org.hibernate.TransientPropertyValueException when updating an existing Interceptor.

**To Reproduce**
1. Go to Interceptors tab in API management screen
2. Click to edit an existing interceptor.
3. Edit any information, then save.
4. See the exception throwing in the api logs. The new data wasn't persisted on database.

**Expected behavior**
The new data are persisted and the interceptor must be updated.

**Screenshots**
![Screenshot from 2019-05-24 14-48-48](https://user-images.githubusercontent.com/1769904/58347020-17d86400-7e33-11e9-903a-98c84e05d7da.png)
![Screenshot from 2019-05-24 14-49-16](https://user-images.githubusercontent.com/1769904/58347039-245cbc80-7e33-11e9-991c-723aac95aeb0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Google Chrome

**Additional context**
I have been updating Heimdall to the latest versions but the error remains :(

**Comment by cassioesp** [comment]
Hi @gBarczyszyn . Thanks for the report!
The pull request associated to this issue is #287 .

**Comment by claytonpiccinin** [comment]
Hello @cassioesp. I'm sorry but I didn't understand what's happened. We was thinking it could be something backend like JPA and persistence without cascade, but the fix came from frontend? 

Could you explain it a little bit more? 

Thanks a lot.

**Comment by cassioesp** [comment]
Hi @claytonpiccinin , sure!

Before the correction, when you edit an interceptor with an environment attached, the environmentId (on the front) is just setted when saved for the first time. When you are updating an interceptor, it was not setting environmentId variable correctly (it was passing null value even if the interceptor had an environment) and this was causing the exception on the API side.

I hope I made it more clear to undestand.

**Comment by claytonpiccinin** [comment]
Ok @cassioesp .
First of all, thank you for your time and availability. 

Do you know when it fix will become available?

**Comment by cassioesp** [comment]
@claytonpiccinin this pull request will be merged to hotfix branch in the next days maybe this week.
But to master branch will take a time because we're on a freezing period.

**Comment by gBarczyszyn** [comment]
@cassioesp Thank you! ;)

**Comment by cassioesp** [comment]
The pull request #287 was merged to master and this issue will be closed.

**Comment by MAAARKIN** [comment]
exactly this PR #287 is fixed.
